[package]
name = "flint-contracts"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["protocol"]
protocol = ["dep:bytes", "dep:prost", "dep:tokio-util", "dep:tokio", "dep:futures-util", "dep:serde_with"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, optional = true }
strum = { workspace = true, features = ["derive"] }
bytes = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["codec"], optional = true }
tokio = { workspace = true, features = ["io-util", "time"], optional = true }
futures-util = { workspace = true, features = ["sink"], optional = true }
