[package]
name = "flint-control-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
flint-config.workspace = true
flint-contracts = { workspace = true, features = ["protocol"] }
tokio = { workspace = true, features = ["rt", "net", "time"] }
futures-util = { workspace = true, features = ["sink"] }
uuid = { workspace = true, features = ["v4"] }
serde_json.workspace = true
fs2.workspace = true
anyhow.workspace = true
