# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flint_protocol/v1/host.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flint_protocol.v1 import common_pb2 as flint__protocol_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66lint_protocol/v1/host.proto\x12\x11\x66lint_protocol.v1\x1a\x1e\x66lint_protocol/v1/common.proto\"\xa4\x01\n\x10RegisterInstance\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x11\n\tname_hint\x18\x02 \x01(\t\x12\x15\n\rinstance_name\x18\x03 \x01(\t\x12\x15\n\rinstance_type\x18\x04 \x01(\t\x12\x11\n\tbridge_id\x18\x05 \x01(\t\x12\x17\n\x0fruntime_version\x18\x06 \x01(\t\x12\x16\n\x0e\x62ridge_version\x18\x07 \x01(\t\"S\n\x18RegisterExecutionChannel\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x15\n\rsession_token\x18\x03 \x01(\t\" \n\tHeartbeat\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"\x97\x01\n\x0bInstanceAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x30\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x1c.flint_protocol.v1.ErrorCodeH\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0binstance_id\x18\x04 \x01(\t\x12\x15\n\rsession_token\x18\x05 \x01(\tB\x08\n\x06_error\"\xa1\x01\n\x12HostExecuteRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x03 \x01(\t\x12\x1b\n\x0e\x65xecution_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x66ilename\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x11\n\x0f_execution_nameB\x0b\n\t_filename\"\x80\x01\n\x15\x45xecutionOutputUpdate\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x14\n\x0cstdout_delta\x18\x04 \x01(\t\x12\x14\n\x0cstderr_delta\x18\x05 \x01(\tB\x14\xaa\x02\x11\x46lint.Protocol.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flint_protocol.v1.host_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021Flint.Protocol.V1'
  _globals['_REGISTERINSTANCE']._serialized_start=84
  _globals['_REGISTERINSTANCE']._serialized_end=248
  _globals['_REGISTEREXECUTIONCHANNEL']._serialized_start=250
  _globals['_REGISTEREXECUTIONCHANNEL']._serialized_end=333
  _globals['_HEARTBEAT']._serialized_start=335
  _globals['_HEARTBEAT']._serialized_end=367
  _globals['_INSTANCEACK']._serialized_start=370
  _globals['_INSTANCEACK']._serialized_end=521
  _globals['_HOSTEXECUTEREQUEST']._serialized_start=524
  _globals['_HOSTEXECUTEREQUEST']._serialized_end=685
  _globals['_EXECUTIONOUTPUTUPDATE']._serialized_start=688
  _globals['_EXECUTIONOUTPUTUPDATE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
