[package]
name = "flint"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
test-runtime = ["flint-config/test-runtime"]

[dependencies]
flint-backend.workspace = true
flint-config.workspace = true
flint-control-client.workspace = true
flint-hosts.workspace = true
flint-contracts = { workspace = true, features = ["protocol"] }
tauri = { workspace = true, features = ["tray-icon"] }
tauri-plugin-decoration.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "time"] }
serde_json.workspace = true
strum.workspace = true
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true
base64 = "0.22"

[build-dependencies]
tauri-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
wait-timeout.workspace = true

[[test]]
name = "product"
path = "../../../tests/main.rs"
required-features = ["test-runtime"]
