[package]
name = "flint"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[dependencies]
flint-core.workspace = true
flint-control-client.workspace = true
flint-connect.workspace = true
flint-protocol.workspace = true
tauri = { workspace = true, features = ["tray-icon"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "time"] }
serde_json.workspace = true
clap = { workspace = true, features = ["derive"] }
anyhow.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
wait-timeout.workspace = true

[[test]]
name = "product"
path = "../../../tests/main.rs"
